name: Build index.json

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v5

      - name: Install Blender
        uses: bradyajohnston/setup-blender@v3
        with:
          version: "4.5"  # replace with the exact Blender version you want

      - name: build index.json
        run: |
          blender --command extension server-generate --repo-dir=docs/

